import "src/styles/globals.css";

import { Inter, Roboto, Abhaya_Libre } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

import { TRPCReactProvider } from "src/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Magada Coocking",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className={`text-clOne`}>
        <Header />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Footer />
      </body>
    </html>
  );
}
